steps:
  # Step to build the base image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/base', '-f', './dockerfiles/base.dockerfile', '.']
    
  # Step to build the train image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$train_repo/$device:latest', '-f', './dockerfiles/trainer.dockerfile', '--build-arg', 'BASE_IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/base', '.']

  # Step to push the train image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$train_repo/$device:latest']

  # Build the deploy container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$deploy_repo/$device:latest', '-f', 'dockerfiles/deploy.dockerfile', '--build-arg', 'BASE_IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/base', '.']

  # Push the deploy container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$deploy_repo/$device:latest']

# Define the source location in your repository
source:
  repoSource:
    repoName: 'MLOPS-TINYSTORIES'
    branchName: 'production'  # You can specify a branch, tag, or commit
    dir: 'dockerfiles'  # Directory where the Dockerfile is located

# Define substitutions, like project ID
substitutions:
  _PROJECT_ID: 'mlops-tiny-stories'
  _train_repo: 'train'
  _deploy_repo: 'deploy'
  _device: 'cpu'

# Specify images to be stored in Artifact Registry
images:
  - 'eu.artifact-registry.googleapis.com/$PROJECT_ID/base'
  - 'eu.artifact-registry.googleapis.com/$PROJECT_ID/train:latest'
  - 'eu.artifact-registry.googleapis.com/$PROJECT_ID/mlops-tinystories:deploy'