steps:
  # Step to build the base image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/base', '-f', './dockerfiles/base.dockerfile', '.']
    
  # Step to build the train image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/Train:latest', '-f', './dockerfiles/trainer.dockerfile', '--build-arg', 'BASE_IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/base', '.']

  # Step to push the train image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/Train:latest']

  # Build the deploy container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/Deploy:latest', '-f', 'dockerfiles/deploy.dockerfile', '--build-arg', 'BASE_IMAGE=us-central1-docker.pkg.dev/$PROJECT_ID/base', '.']

  # Push the deploy container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/Deploy:latest']



# Define substitutions, like project ID
substitutions:
  _PROJECT_ID: 'mlops-tiny-stories'
  _REPO_NAME: 'cpu'


