name: Ruff
on: pull_request
jobs:
  ruff:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - run: |
          ls

      - uses: chartboost/ruff-action@v1
        with:
          version: 0.1.11
          args: check --config pyproject.toml