name: Ruff
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Check for CRLF endings
        uses: erclu/check-crlf@v1

      - uses: chartboost/ruff-action@v1
        with:
          src: "mlopstinystories"