name: Ruff
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - run: |
          ls
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          src: "mlopstinystories"
          python-version: 3.11.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt
      
      - name: Run Ruff
        run: |
          ruff check mlopstinystories
