name: Ruff
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - run: |
          cat mlopstinystories/train_model.py
          
      - uses: chartboost/ruff-action@v1
        with:
          src: "mlopstinystories"
          args: --fix
      
      - run: |
          cat mlopstinystories/train_model.py