name: Ruff
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - run: |
          ls

      - uses: chartboost/ruff-action@v1
        with:
          args: check --config pyproject.toml