name: Ruff
on: pull_request
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: chartboost/ruff-action@v1
        with:
          args: --config pyproject.toml check