name: Ruff
on: 
  pull_request:
    paths:
      - '**.py'
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: chartboost/ruff-action@v1
        with:
          src: "mlops-tinystories"